### PR TITLE
Sync tab , Search Key tab, Sync Key tab - - seperate tab and gui tweaks

### PR DESCRIPTION
**Pull request by vritant**

### CODE REVIEW

**Comment by ykoer** [comment]
1) Sync Tab:
- I would align the form fields to top. It looks bad when you make the text area bigger.

2) Sync Keys and Metadata Management Tabs:
- I know this will be addressed by the UX team. But can we make the green and blue buttons little bit smaller now. They are too big compared to other form fields.
- its not clear to the user what Name and Value is for. We should make it clear in the UI, e.g. showing a popup when the user hovers over it.
- There is the possibility select 'View' from the context menu even if it is a leave node. Can we make that inactive or even not show it?
- 'View' is confusing for me. How about "Edit Child's"
- I know we had that discussion about back button. I always click on the back button and not the breadcrumb. Since AngularJS can deal with it, why not use both navigation methods? 
- SyncKeysCtrl and MetadataCtrl share a lot of common functions. Did think about a common controller which is extended by SyncKeysCtrl and SearchKeysCtrl?

**Comment by vritant** [comment]
@ykoer I have made changes to update all of the above points except the last two.

w.r.t back button, considering we have at least one way of traversing I have opened #16  to tackle this later when we have more time, given certain caveats.

w.r.t a common controller, the methods are similarly named cause they perform similar functions, but each method's implementation is subtly different in small ways. this means that having a common controller with shared methods and specific fine grained overridden methods will complicate the code more than simplify things.

**Comment by vritant** [comment]
@derek63  do you mind taking a look at this pull request and merging ? based on above conversation I suppose review is complete.

**Comment by vritant** [comment]
@derek63  and @ykoer , merging this pull request to reduce branch complications, especially since I have made changes already according to the review. however, have created a branch feature-sync-searchkey-gui-review incase we need a third look. please create issues for further changes required.

code being merged in : 
 from commit: 8966fd5b2501fa0e557baeee3d4f668899f66e7d
to commit: 6a68e6a72bf88f2311a9acd10dc31d61423c9f88

**Pull request merged**
