### PR TITLE
Case insensitive search

### PR DESCRIPTION
**Pull request by derek63**

### CODE REVIEW

**Comment by vritant** [comment]
@derek63  The changes look good. :+1:  But I have two further changes to propose : 
1. while search is correctly insensitive in this pull request , Ive observed that when the case does not match a pre-defined SearchField enum type, we are falling back to a custom field.
While this may work if a header is set on a message for that custom search criterion, I deployed this , and found that there is an observable difference in response time when the search criteria is realized as a pre-defined field vs. a custom field.

I suggest we change SearchField.java to realize a search criteria as predefined field irrespective of the case. this way , we can search on ESB_MESSAGE table if possible . the find method in SearchField is not used in the current code, we could change it to use it for this purpose.

2. I might be wrong , but I think suggestions for values are showing up only when the case of the search key matches what is returned by the current suggestions API . I would recommend changing the angular code to make suggestions for values show up irrespective of the case of the search key.

SInce the commits in this request are perfect, I could accept this and simply create issues for these items.. lemme know if you would like me to do so!

**Comment by derek63** [comment]
@vritant, thanks for the review, I will go ahead and make your suggested updates and include them with this PR.

**Comment by derek63** [comment]
@vritant I updated the SearchField to ignore case when determining whether or not a field is predefined, and created some tests for that class.  It seems like the Angular typeahead/autocomplete default behavior is to ignore case (and it appears to work this way on my local instance of the app), so I think we are good in for this change.  Please have a look at the changes on your end and confirm at your earliest convenience.

**Comment by vritant** [comment]
Thanks @derek63

**Pull request merged**
